[package]
name = "fossil-lsp"
version.workspace = true
description = "Error-tolerant analysis for Fossil language editor support"
homepage.workspace = true
repository.workspace = true
documentation.workspace = true
license.workspace = true
categories.workspace = true
keywords.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

[features]
utoipa = ["dep:utoipa"]

[dependencies]
fossil-lang.workspace = true
serde = { version = "1", features = ["derive"] }
miette = "7"
utoipa = { version = "5", optional = true }
