[package]
name = "fossil-stdlib"
version.workspace = true
description.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true
license.workspace = true
categories.workspace = true
keywords.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
# external dependencies
thiserror.workspace = true
unicode-normalization = "0.1"
polars.workspace = true
duckdb = { version = "1.2", features = ["bundled"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yml = "0.0.12"

sha2 = "0.10"

# internal dependencies
fossil-lang.workspace = true
fossil-macros.workspace = true
